// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtsjhrhhbwxoxsysxfku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0c2pocmhoYnd4b3hzeXN4Zmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTQ4NDUsImV4cCI6MjA2NzEzMDg0NX0.TJE9CxEGR4XejWScB7G1-ywu7yI0D7iFz6JhxH9q2ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});